server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#registerWithEureka与fetchRegistry用于表明自己是一个eureka server
spring:
  application:
    name: eurka-server